vim.opt.breakindent = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.colorcolumn = '80'
vim.opt.wrapmargin = 80
vim.opt.undofile = true
vim.opt.undodir = os.getenv('HOME') .. '/.local/state/nvim/undo/'
vim.opt.shiftwidth = 4
vim.opt.softtabstop = 4
vim.opt.shiftround = true
vim.opt.backup = true
vim.opt.backupdir = os.getenv('HOME') .. '/.local/state/nvim/backup/'
vim.opt.splitright = true
